const ordersData = [
  {
    id: 'A-10245',
    description: 'Шкаф-купе стандартный',
    createdAt: new Date('2025-10-14'),
    author: 'Сахоненко Мария',
    photoLink: '',
    clientName: 'Сахоненко Мария',
    clientAddress: 'ул. Пушкина 29, Минск',
    clientPhone: '+375291234567',
    furnitureType: 'Шкаф-купе',
    material: 'Дуб, фурнитура Hettich',
    size: '200x220x60 см',
    quantity: 2,
    cost: 1500,
    status: 'в очереди',
    paymentMethod: 'банковский перевод',
    prepaymentPercent: 30,
    installCost: 250
  },
  {
    id: 'B-77310',
    description: 'Кухонный гарнитур угловой',
    createdAt: new Date('2025-09-28'),
    author: 'Липкина Диана',
    photoLink: '',
    clientName: 'Липкина Диана',
    clientAddress: 'ул. Ленина 15, Орша',
    clientPhone: '+375292345678',
    furnitureType: 'Кухонный гарнитур',
    material: 'Ясень, фурнитура Blum',
    size: '300x220x60 см',
    quantity: 1,
    cost: 2500,
    status: 'в работе',
    paymentMethod: 'наличные',
    prepaymentPercent: 50,
    installCost: 400
  },
  {
    id: 'C-55123',
    description: 'Офисный стол',
    createdAt: new Date('2025-10-10'),
    author: 'Бень Марк',
    photoLink: '',
    clientName: 'Бень Марк',
    clientAddress: 'ул. Варвашени 10, Барановичи',
    clientPhone: '+375293456789',
    furnitureType: 'Стол',
    material: 'Стекло, металл',
    size: '160x80x75 см',
    quantity: 3,
    cost: 1200,
    status: 'завершен',
    paymentMethod: 'карта',
    prepaymentPercent: 100,
    installCost: 150
  },
  {
    id: 'D-88199',
    description: 'Тумба под ТВ',
    createdAt: new Date('2025-10-05'),
    author: 'Салата Анна',
    photoLink: '',
    clientName: 'Салата Анна',
    clientAddress: 'ул. Мира 12, Брест',
    clientPhone: '+375294567890',
    furnitureType: 'Тумба',
    material: 'МДФ, пластик',
    size: '180x50x40 см',
    quantity: 1,
    cost: 700,
    status: 'в очереди',
    paymentMethod: 'наличные',
    prepaymentPercent: 40,
    installCost: 100
  },
  {
    id: 'E-33456',
    description: 'Детский шкаф',
    createdAt: new Date('2025-09-15'),
    author: 'Козлова Елена',
    photoLink: '',
    clientName: 'Козлова Елена',
    clientAddress: 'пр. Независимости 100, Минск',
    clientPhone: '+375295678901',
    furnitureType: 'Шкаф-купе',
    material: 'ЛДСП, пластик',
    size: '150x200x55 см',
    quantity: 1,
    cost: 900,
    status: 'в работе',
    paymentMethod: 'банковский перевод',
    prepaymentPercent: 60,
    installCost: 180
  },
  {
    id: 'F-66778',
    description: 'Кухня линейная',
    createdAt: new Date('2025-10-01'),
    author: 'Новиков Алексей',
    photoLink: '',
    clientName: 'Новиков Алексей',
    clientAddress: 'ул. Октябрьская 33, Гродно',
    clientPhone: '+375296789012',
    furnitureType: 'Кухонный гарнитур',
    material: 'МДФ, акрил',
    size: '320x220x60 см',
    quantity: 1,
    cost: 3200,
    status: 'в очереди',
    paymentMethod: 'карта',
    prepaymentPercent: 35,
    installCost: 450
  },
  {
    id: 'G-11223',
    description: 'Компьютерный стол',
    createdAt: new Date('2025-09-20'),
    author: 'Морозова Ольга',
    photoLink: '',
    clientName: 'Морозова Ольга',
    clientAddress: 'ул. Фрунзе 8, Могилев',
    clientPhone: '+375297890123',
    furnitureType: 'Стол',
    material: 'ДСП, металл',
    size: '140x70x75 см',
    quantity: 2,
    cost: 850,
    status: 'завершен',
    paymentMethod: 'наличные',
    prepaymentPercent: 100,
    installCost: 120
  },
  {
    id: 'H-44556',
    description: 'Прихожая гарнитур',
    createdAt: new Date('2025-10-12'),
    author: 'Волков Дмитрий',
    photoLink: '',
    clientName: 'Волков Дмитрий',
    clientAddress: 'ул. Калинина 67, Минск',
    clientPhone: '+375298901234',
    furnitureType: 'Шкаф-купе',
    material: 'ЛДСП, зеркало',
    size: '250x220x60 см',
    quantity: 1,
    cost: 1800,
    status: 'в очереди',
    paymentMethod: 'банковский перевод',
    prepaymentPercent: 45,
    installCost: 300
  },
  {
    id: 'I-77889',
    description: 'Журнальный столик',
    createdAt: new Date('2025-09-25'),
    author: 'Павлова Ирина',
    photoLink: '',
    clientName: 'Павлова Ирина',
    clientAddress: 'ул. Ленинградская 22, Витебск',
    clientPhone: '+375299012345',
    furnitureType: 'Стол',
    material: 'Дерево, стекло',
    size: '100x60x45 см',
    quantity: 1,
    cost: 550,
    status: 'в работе',
    paymentMethod: 'карта',
    prepaymentPercent: 70,
    installCost: 80
  },
  {
    id: 'J-99001',
    description: 'Тумба в ванную',
    createdAt: new Date('2025-10-08'),
    author: 'Федоров Сергей',
    photoLink: '',
    clientName: 'Федоров Сергей',
    clientAddress: 'ул. Богдановича 15, Минск',
    clientPhone: '+375290123456',
    furnitureType: 'Тумба',
    material: 'Влагостойкий МДФ',
    size: '80x50x45 см',
    quantity: 1,
    cost: 450,
    status: 'в очереди',
    paymentMethod: 'наличные',
    prepaymentPercent: 50,
    installCost: 90
  },
  {
    id: 'K-22334',
    description: 'Угловой шкаф в спальню',
    createdAt: new Date('2025-09-30'),
    author: 'Семенова Татьяна',
    photoLink: '',
    clientName: 'Семенова Татьяна',
    clientAddress: 'ул. Купалы 18, Гродно',
    clientPhone: '+375291234567',
    furnitureType: 'Шкаф-купе',
    material: 'Массив ольхи',
    size: '280x240x60 см',
    quantity: 1,
    cost: 2900,
    status: 'в работе',
    paymentMethod: 'банковский перевод',
    prepaymentPercent: 55,
    installCost: 350
  },
  {
    id: 'L-55667',
    description: 'Обеденный стол',
    createdAt: new Date('2025-10-03'),
    author: 'Ковалев Андрей',
    photoLink: '',
    clientName: 'Ковалев Андрей',
    clientAddress: 'ул. Победы 77, Брест',
    clientPhone: '+375292345678',
    furnitureType: 'Стол',
    material: 'Дуб, металл',
    size: '200x100x75 см',
    quantity: 1,
    cost: 1600,
    status: 'в очереди',
    paymentMethod: 'карта',
    prepaymentPercent: 65,
    installCost: 200
  },
  {
    id: 'M-88990',
    description: 'Кухня с барной стойкой',
    createdAt: new Date('2025-09-18'),
    author: 'Орлова Мария',
    photoLink: '',
    clientName: 'Орлова Мария',
    clientAddress: 'пр. Пушкина 44, Минск',
    clientPhone: '+375293456789',
    furnitureType: 'Кухонный гарнитур',
    material: 'МДФ, пластик',
    size: '350x240x60 см',
    quantity: 1,
    cost: 3800,
    status: 'завершен',
    paymentMethod: 'наличные',
    prepaymentPercent: 100,
    installCost: 500
  },
  {
    id: 'N-11234',
    description: 'Комод в спальню',
    createdAt: new Date('2025-10-06'),
    author: 'Григорьев Иван',
    photoLink: '',
    clientName: 'Григорьев Иван',
    clientAddress: 'ул. Якуба Коласа 25, Минск',
    clientPhone: '+375294567890',
    furnitureType: 'Тумба',
    material: 'ЛДСП, ткань',
    size: '120x80x45 см',
    quantity: 1,
    cost: 750,
    status: 'в очереди',
    paymentMethod: 'банковский перевод',
    prepaymentPercent: 40,
    installCost: 110
  },
  {
    id: 'O-44567',
    description: 'Стеллаж для книг',
    createdAt: new Date('2025-09-22'),
    author: 'Данькова Екатерина',
    photoLink: '',
    clientName: 'Данькова Екатерина',
    clientAddress: 'ул. Первомайская 13, Витебск',
    clientPhone: '+375295678901',
    furnitureType: 'Шкаф-купе',
    material: 'ДСП, стекло',
    size: '180x200x35 см',
    quantity: 2,
    cost: 1300,
    status: 'в работе',
    paymentMethod: 'карта',
    prepaymentPercent: 75,
    installCost: 220
  },
  {
    id: 'P-77890',
    description: 'Письменный стол',
    createdAt: new Date('2025-10-09'),
    author: 'Белов Павел',
    photoLink: '',
    clientName: 'Белов Павел',
    clientAddress: 'ул. Сурганова 5, Минск',
    clientPhone: '+375296789012',
    furnitureType: 'Стол',
    material: 'Массив бука',
    size: '150x75x78 см',
    quantity: 1,
    cost: 1400,
    status: 'в очереди',
    paymentMethod: 'наличные',
    prepaymentPercent: 60,
    installCost: 170
  },
  {
    id: 'Q-22345',
    description: 'Гардеробная система',
    createdAt: new Date('2025-09-28'),
    author: 'Медведева Светлана',
    photoLink: '',
    clientName: 'Медведева Светлана',
    clientAddress: 'ул. Варвашени 9, Гродно',
    clientPhone: '+375297890123',
    furnitureType: 'Шкаф-купе',
    material: 'ЛДСП, система комбинаций',
    size: '300x250x65 см',
    quantity: 1,
    cost: 4200,
    status: 'в работе',
    paymentMethod: 'банковский перевод',
    prepaymentPercent: 80,
    installCost: 550
  },
  {
    id: 'R-55678',
    description: 'Кухня островная',
    createdAt: new Date('2025-10-11'),
    author: 'Алексеев Николай',
    photoLink: '',
    clientName: 'Алексеев Николай',
    clientAddress: 'ул. Космонавтов 21, Могилев',
    clientPhone: '+375298901234',
    furnitureType: 'Кухонный гарнитур',
    material: 'МДФ, камень',
    size: '400x240x90 см',
    quantity: 1,
    cost: 5500,
    status: 'в очереди',
    paymentMethod: 'карта',
    prepaymentPercent: 70,
    installCost: 700
  },
  {
    id: 'S-88901',
    description: 'Туалетный столик',
    createdAt: new Date('2025-09-24'),
    author: 'Полякова Анна',
    photoLink: '',
    clientName: 'Полякова Анна',
    clientAddress: 'ул. Притыцкого 33, Минск',
    clientPhone: '+375299012345',
    furnitureType: 'Тумба',
    material: 'МДФ, зеркало',
    size: '100x45x75 см',
    quantity: 1,
    cost: 950,
    status: 'завершен',
    paymentMethod: 'наличные',
    prepaymentPercent: 100,
    installCost: 130
  },
  {
    id: 'T-33456',
    description: 'Консоль в прихожую',
    createdAt: new Date('2025-10-07'),
    author: 'Васильев Максим',
    photoLink: '',
    clientName: 'Васильев Максим',
    clientAddress: 'ул. Лобанка 17, Витебск',
    clientPhone: '+375290123456',
    furnitureType: 'Тумба',
    material: 'Массив дуба',
    size: '120x35x80 см',
    quantity: 1,
    cost: 1100,
    status: 'в очереди',
    paymentMethod: 'банковский перевод',
    prepaymentPercent: 50,
    installCost: 150
  }
];
